-- AlterTable
ALTER TABLE "OrderItems" ALTER COLUMN "estimatedProductTotalPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "productTotalPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Orders" ALTER COLUMN "orderTotalPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "estimatedOrderPrice" SET DATA TYPE DOUBLE PRECISION;
